notes: "CL naive baseline"
entity: "frozenwolf"
device: cuda
batch_size: 20
num_workers: 0
learning_rate: 0.0001
epochs: 5
distributed: true
mixed_precision: true

output_dir: "output"
# output_dir: "/scratch/gokuladethya.cse.nitt/indiaai/output"

model:
  freeze_encoder_till: 12

dataset:
  path: "/home/frozenwolf/Desktop/indiaai_subset/"
  annotation_path: "/home/frozenwolf/Desktop/dataset.pkl"
  # path: "../"

cl_config:
  evaluate_every_n_epochs: 10
  knowledge_distillation: 0.1

cl_kmean:
  reset_lora: true
  knowledge_distillation: false
