notes: "CL naive baseline"
entity: "frozenwolf"
device: cuda
batch_size: 32
num_workers: 0
learning_rate: 0.0001
epochs: 100
distributed: true
mixed_precision: true
save_weights: false #===============================
evaluate_every_n_epochs: 2
# output_dir: "output"
output_dir: "/scratch/gokuladethya.cse.nitt/indiaai/output"

model:
  freeze_encoder_till: 12

dataset:
  path: "/scratch/gokuladethya.cse.nitt/indiaai_subset/"
  annotation_path: "/scratch/gokuladethya.cse.nitt/dataset.pkl"
  train_size: 3000
  # path: "/home/frozenwolf/Desktop/indiaai_subset/"
  # annotation_path: "/home/frozenwolf/Desktop/dataset.pkl"
  # path: "../"
